### ISSUE TITLE
Galaxy reports sample ini file is no good.

### ISSUE THREAD

**Issue by Slugger70** [gvlproject/gvl_image_playbook#43]
The reports.ini.sample file is not working. It gets an error:

```
Traceback (most recent call last):
  File "./scripts/paster.py", line 26, in 
    serve.run()
  File "/mnt/galaxy/galaxy-app/lib/galaxy/util/pastescript/serve.py", line 1061, in run
    invoke(command, command_name, options, args[1:])
  File "/mnt/galaxy/galaxy-app/lib/galaxy/util/pastescript/serve.py", line 1067, in invoke
    exit_code = runner.run(args)
  File "/mnt/galaxy/galaxy-app/lib/galaxy/util/pastescript/serve.py", line 223, in run
    result = self.command()
  File "/mnt/galaxy/galaxy-app/lib/galaxy/util/pastescript/serve.py", line 637, in command
    server = loadserver(server_spec, name=server_name, relative_to=base, global_conf=vars)
  File "/mnt/galaxy/galaxy-app/lib/galaxy/util/pastescript/loadwsgi.py", line 300, in loadserver
    return loadobj(SERVER, uri, name=name, **kw)
  File "/mnt/galaxy/galaxy-app/lib/galaxy/util/pastescript/loadwsgi.py", line 316, in loadobj
    global_conf=global_conf)
  File "/mnt/galaxy/galaxy-app/lib/galaxy/util/pastescript/loadwsgi.py", line 341, in loadcontext
    global_conf=global_conf)
  File "/mnt/galaxy/galaxy-app/lib/galaxy/util/pastescript/loadwsgi.py", line 365, in _loadconfig
    return loader.get_context(object_type, name, global_conf)
  File "/mnt/galaxy/galaxy-app/lib/galaxy/util/pastescript/loadwsgi.py", line 453, in get_context
    object_type, name=name)
  File "/mnt/galaxy/galaxy-app/lib/galaxy/util/pastescript/loadwsgi.py", line 632, in find_config_section
    self.filename))
LookupError: No section 'main' (prefixed by 'server') found in config /mnt/galaxy/galaxy-app/config/reports.ini.sample
Removing PID file reports_webapp.pid
```

The file is correct in the build images (or at least it is in the mGVL) but seems to be changed post launch.

Not sure what is going on.

**Comment by Slugger70** [comment]
If I overwrite the file with the working version, it gets reoverwritten with the broken one whenever I try a retart in cloudman.. The only way I can get it to work is to over write it and then remove write permissions on the file...

**Comment by Slugger70** [comment]
working version contents:

```
[server:main]
use = egg:Paste#http
port = 9001
host = 127.0.0.1
use_threadpool = true
threadpool_workers = 10

[filter:proxy-prefix]
use = egg:PasteDeploy#prefix
prefix = /reports

[app:main]
paste.app_factory = galaxy.webapps.reports.buildapp:app_factory
log_level = DEBUG
use_beaker_session = True
session_type = memory
session_data_dir = %(here)s/database/beaker_sessions
session_key = galaxysessions
session_secret = changethisinproduction
use_lint = false
sendmail_path = /usr/sbin/sendmail
mailing_join_addr = galaxy-user-join@bx.psu.edu
use_new_layout = true
filter-with = proxy-prefix
new_file_path = /mnt/galaxy/tmp
database_connection = postgres://galaxy@localhost:5930/galaxy
file_path = /mnt/galaxy/files
```

**Comment by nuwang** [comment]
Caused by incompatibility between cloudman and latest galaxy. (reports_wsgi.ini renamed to reports.ini). Fixed
