### ISSUE TITLE
no module _rpy3030

### ISSUE THREAD

**Issue by igormakunin** [gvlproject/gvl_image_playbook#45]
Error with Graph > Scatterplot:
Traceback (most recent call last):
  File "/mnt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/scatterplot/d243056b22ed/scatterplot/scatterplot.py", line 5, in <module>
    from rpy import *
  File "/mnt/galaxy/tools/rpy/1.0.3/devteam/package_rpy_1_0_3/82170c94ca7c/lib/python/rpy.py", line 134, in <module>
    """ % RVERSION)
RuntimeError: No module named _rpy3030

**Comment by jessicachung** [comment]
Duplicate of https://github.com/gvlproject/gvl.ansible.playbook/issues/39
